# Generated by Django 2.0.5 on 2018-05-21 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cu_date_added', models.DateField(auto_now_add=True)),
                ('cu_date_last_changed', models.DateField(auto_now=True)),
                ('cu_first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('cu_last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('cu_middle_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Middle Name')),
                ('cu_suffix', models.CharField(blank=True, max_length=200, null=True, verbose_name='Suffix')),
                ('cu_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('cu_address_line_1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address Line 1')),
                ('cu_address_line_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address Line 2')),
                ('cu_city', models.CharField(blank=True, max_length=200, null=True, verbose_name='City')),
                ('cu_state', models.CharField(blank=True, default='TX', max_length=2, null=True, verbose_name='State')),
                ('cu_zip', models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip')),
                ('cu_country', models.CharField(blank=True, default='USA', max_length=200, null=True, verbose_name='Country')),
                ('cu_county', models.CharField(blank=True, max_length=200, null=True, verbose_name='County')),
                ('cu_phone_primary', models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone')),
                ('cu_photo_id_number', models.CharField(blank=True, max_length=8, null=True, verbose_name="Driver's License/ID Number")),
                ('cu_photo_id_type', models.CharField(blank=True, choices=[('DRIVERS_LICENSE', "U.S. Driver's License/ID Card"), ('MILITARY_ID', 'U.S. Military ID'), ('DOJ_ID', 'U.S. Citizenship & Immigration Services/DOJ ID'), ('NATO_ID', 'NATO ID'), ('DOS_ID', 'U.S. Department of State ID')], default='DRIVERS_LICENSE', max_length=200, null=True, verbose_name='ID Type')),
                ('cu_photo_id_state', models.CharField(blank=True, max_length=2, null=True, verbose_name='ID State')),
                ('cu_flag_military', models.NullBooleanField(verbose_name='Are you military personel stationed in Texas?')),
            ],
        ),
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('v_date_added', models.DateField(auto_now_add=True)),
                ('v_date_last_changed', models.DateField(auto_now=True)),
                ('v_vin', models.CharField(blank=True, max_length=17, null=True, verbose_name='Vehicle Identification Number')),
                ('v_year', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Year')),
                ('v_make', models.CharField(blank=True, max_length=200, null=True, verbose_name='Make')),
                ('v_body_style', models.CharField(blank=True, max_length=200, null=True, verbose_name='Body Style')),
                ('v_model', models.CharField(blank=True, max_length=200, null=True, verbose_name='Model')),
                ('v_purchased_from_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Seller Name')),
                ('v_purchased_from_city', models.CharField(blank=True, max_length=200, null=True, verbose_name='City Purchased From')),
                ('v_purchased_from_state', models.CharField(blank=True, max_length=200, null=True, verbose_name='State Purchased From')),
                ('v_odometer_reading', models.IntegerField(blank=True, null=True, verbose_name='Odometer Reading')),
                ('v_purchase_date', models.DateField(blank=True, null=True, verbose_name='Purchase Date')),
                ('v_purchase_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Purchase Price (USD)')),
                ('v_plate_number', models.CharField(blank=True, max_length=8, null=True, verbose_name='License Plate Number')),
                ('v_empty_weight', models.IntegerField(blank=True, null=True, verbose_name='Empty Weight')),
                ('v_lienholder_name_first', models.CharField(blank=True, default='N/A', max_length=200, null=True, verbose_name='Lienholder Name (First)')),
                ('v_seller_signature', models.CharField(blank=True, default='UNAVAILABLE', max_length=200, null=True, verbose_name='Seller Signature')),
                ('v_bond_request_explanation', models.TextField(blank=True, null=True, verbose_name='Provide an explanation for requesting a bonded title or tax assessor-collector hearing.')),
                ('v_flag_last_titled_in_tx', models.NullBooleanField(verbose_name='Was the vehicle last titled in Texas?')),
                ('v_flag_abandoned', models.NullBooleanField(verbose_name='Is the vehicle an abandoned vehicle?')),
                ('v_flag_subject_to_charges', models.NullBooleanField(verbose_name="Is the vehicle subject to storage or mechanic's charges?")),
                ('v_flag_subject_to_lien', models.NullBooleanField(verbose_name='Is the vehicle subject to any type of foreclosure lien?')),
                ('v_flag_nonrepairable', models.NullBooleanField(verbose_name='Is the vehicle a nonrepairable vehicle?')),
                ('v_flag_salvage', models.NullBooleanField(verbose_name='Is the vehicle a salvage vehicle?')),
                ('v_flag_pending_lawsuits', models.NullBooleanField(verbose_name='Is the vehicle involved in any pending lawsuits or disputes of ownership?')),
                ('v_flag_legal_posession', models.NullBooleanField(verbose_name='Are you in legal possession of the vehicle?')),
                ('v_flag_legal_control', models.NullBooleanField(verbose_name='Are you in legal control of the vehicle?')),
                ('v_flag_manufactured_us', models.NullBooleanField(verbose_name='Was the vehicle manufactured for sale or distribution in the United States by a motor vehicle manufacturer?')),
                ('v_flag_assembled', models.NullBooleanField(verbose_name='Is the vehicle an assembled vehicle from new or used part(s) or a kit that has not been previously titled?')),
                ('v_flag_complete', models.NullBooleanField(verbose_name='Is the vehicle complete?')),
                ('v_flag_25_or_older', models.NullBooleanField(verbose_name='Is the vehicle 25 or more years old?')),
                ('v_flag_no_plates', models.CharField(blank=True, choices=[('HAS_PLATES', 'License plates and registration issued for this vehicle are being surrendered. The registration for this vehicle is not currently suspended or revoked.'), ('NO_PLATES', 'Vehicle has no license plates and/or registration.'), ('MIL_PLATES', 'Vehicle has been issued a license plate under the applicable status of forces agreement.')], max_length=200, null=True, verbose_name='Please select one:')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EzForm.Customer')),
            ],
        ),
    ]
