# Generated by Django 2.0.5 on 2018-05-23 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EzForm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcctForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acct_date_added', models.DateField(auto_now_add=True)),
                ('acct_date_last_changed', models.DateField(auto_now=True)),
                ('acct_vin', models.CharField(blank=True, max_length=17, null=True, verbose_name='Vehicle Identification Number')),
                ('acct_vin_year', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Year')),
                ('acct_vin_make', models.CharField(blank=True, max_length=200, null=True, verbose_name='Make')),
                ('acct_vin_body_style', models.CharField(blank=True, max_length=200, null=True, verbose_name='Body Style')),
                ('acct_vin_model', models.CharField(blank=True, max_length=200, null=True, verbose_name='Model')),
                ('acct_titledocument_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title/Document Number')),
                ('acct_plate_number', models.CharField(blank=True, max_length=8, null=True, verbose_name='License Plate Number')),
                ('acct_agent_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name of Owner, Agent, Lienholder of the Vehicle')),
                ('acct_recipient_first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='First Name')),
                ('acct_recipient_middle_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Middle Name')),
                ('acct_recipient_last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Last Name')),
                ('acct_suffix', models.CharField(blank=True, max_length=200, null=True, verbose_name='Suffix')),
                ('acct_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mailing Address')),
                ('acct_city', models.CharField(blank=True, max_length=200, null=True, verbose_name='City')),
                ('acct_state', models.CharField(blank=True, max_length=2, null=True, verbose_name='State')),
                ('acct_zip', models.CharField(blank=True, max_length=10, null=True, verbose_name='ZIP Code')),
                ('acct_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('acct_phone_primary', models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='cu_zip',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ZIP Code'),
        ),
        migrations.AddField(
            model_name='acctform',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EzForm.Customer'),
        ),
    ]
