# Generated by Django 2.0.5 on 2018-05-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
