# Generated by Django 2.0.5 on 2018-05-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_customer_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cu_address_line_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cu_address_line_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cu_city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cu_country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cu_county',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cu_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cu_flag_military',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cu_middle_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cu_phone_primary',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cu_photo_id_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cu_photo_id_state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cu_state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cu_suffix',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cu_zip',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_body_style',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_bond_request_explanation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_empty_weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_flag_25_or_older',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_flag_abandoned',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_flag_assembled',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_flag_complete',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_flag_last_titled_in_tx',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_flag_legal_control',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_flag_legal_posession',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_flag_manufactured_us',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_flag_no_plates',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_flag_nonrepairable',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_flag_pending_lawsuits',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_flag_salvage',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_flag_subject_to_charges',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_flag_subject_to_lien',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_lienholder_name_first',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_make',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_model',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_odometer_reading',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_plate_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_purchase_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_purchase_price_usd',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_purchased_from_city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_purchased_from_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_purchased_from_state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_seller_signature',
            field=models.CharField(default='UNAVAILABLE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_vin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_year',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
