# Generated by Django 2.0.5 on 2018-05-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180517_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='v_year',
            field=models.IntegerField(null=True),
        ),
    ]
