# Generated by Django 2.0.5 on 2018-05-18 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180517_1957'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicle',
            new_name='Vehicles',
        ),
    ]
