# Generated by Django 2.0.5 on 2018-05-18 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180518_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='v_customer',
        ),
        migrations.DeleteModel(
            name='Vehicles',
        ),
    ]
