# Generated by Django 2.0.5 on 2018-05-18 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180518_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('v_date_added', models.DateField(auto_now_add=True)),
                ('v_date_last_changed', models.DateField(auto_now=True)),
                ('v_vin', models.CharField(max_length=200, null=True)),
                ('v_year', models.IntegerField(null=True)),
                ('v_make', models.CharField(max_length=200, null=True)),
                ('v_body_style', models.CharField(max_length=200, null=True)),
                ('v_model', models.CharField(max_length=200, null=True)),
                ('v_purchased_from_name', models.CharField(max_length=200, null=True)),
                ('v_purchased_from_city', models.CharField(max_length=200, null=True)),
                ('v_purchased_from_state', models.CharField(max_length=200, null=True)),
                ('v_odometer_reading', models.IntegerField(null=True)),
                ('v_purchase_date', models.DateField(null=True)),
                ('v_purchase_price_usd', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('v_plate_number', models.CharField(max_length=200, null=True)),
                ('v_empty_weight', models.IntegerField(null=True)),
                ('v_lienholder_name_first', models.CharField(default='N/A', max_length=200, null=True)),
                ('v_seller_signature', models.CharField(default='UNAVAILABLE', max_length=200, null=True)),
                ('v_bond_request_explanation', models.TextField(null=True)),
                ('v_flag_last_titled_in_tx', models.NullBooleanField()),
                ('v_flag_abandoned', models.NullBooleanField()),
                ('v_flag_subject_to_charges', models.NullBooleanField()),
                ('v_flag_subject_to_lien', models.NullBooleanField()),
                ('v_flag_nonrepairable', models.NullBooleanField()),
                ('v_flag_salvage', models.NullBooleanField()),
                ('v_flag_pending_lawsuits', models.NullBooleanField()),
                ('v_flag_legal_posession', models.NullBooleanField()),
                ('v_flag_legal_control', models.NullBooleanField()),
                ('v_flag_manufactured_us', models.NullBooleanField()),
                ('v_flag_assembled', models.NullBooleanField()),
                ('v_flag_complete', models.NullBooleanField()),
                ('v_flag_25_or_older', models.NullBooleanField()),
                ('v_flag_no_plates', models.NullBooleanField()),
                ('v_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Customer')),
            ],
        ),
    ]
