# Generated by Django 2.0.5 on 2018-05-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20180518_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='v_customer',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
