# Generated by Django 2.0.5 on 2018-05-22 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20180519_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACCT_Form',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acct_date_added', models.DateField(auto_now_add=True)),
                ('acct_first_name', models.CharField(default='blank', max_length=200)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Customer')),
            ],
        ),
    ]
